#! /bin/bash

DATA_FILE=$1
QUERY_STRING=$2

# QUERY_STRING "id=(002,003,004)" --> PATTERN "id=(002|003|004)"
export PATTERN=`echo "$QUERY_STRING" | sed 's/,/|/g'`

echo '# Cardiology patient data'
egrep "$PATTERN" $1
exit 0

